# analysis_options.yaml
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # const rules - مهمة جداً
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true

    # performance rules
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true

    # code quality
    require_trailing_commas: true
    sort_child_properties_last: true

analyzer:
  exclude:
  - "**/*.g.dart"
  - "**/*.freezed.dart"

  errors:
    # جعل const warnings تظهر كـ errors
    prefer_const_constructors: error
    prefer_const_constructors_in_immutables: error
