// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYoNrToJ2ombPSWw1zRB2_Ag3dR9ROlko',
    appId: '1:302709623576:web:b5084ce0557211ad09ec6d',
    messagingSenderId: '302709623576',
    projectId: 'fruit-hub-763b2',
    authDomain: 'fruit-hub-763b2.firebaseapp.com',
    storageBucket: 'fruit-hub-763b2.firebasestorage.app',
    measurementId: 'G-PH6ZGR7WEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8x9P3hgd0kHbX8hxcxhY3rC6VWnMyypg',
    appId: '1:302709623576:android:f87adf49e696850f09ec6d',
    messagingSenderId: '302709623576',
    projectId: 'fruit-hub-763b2',
    storageBucket: 'fruit-hub-763b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtdNI-Q___l88L4cdEF4WIMuJrKX1HE9U',
    appId: '1:302709623576:ios:0eeb5c8e5f1a6a3809ec6d',
    messagingSenderId: '302709623576',
    projectId: 'fruit-hub-763b2',
    storageBucket: 'fruit-hub-763b2.firebasestorage.app',
    androidClientId: '302709623576-op67acv03a8jli7ri4dhagg8l018tuj7.apps.googleusercontent.com',
    iosClientId: '302709623576-tnmk92uu43navv7r4rqj8j0u0vct830k.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboaerd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtdNI-Q___l88L4cdEF4WIMuJrKX1HE9U',
    appId: '1:302709623576:ios:0eeb5c8e5f1a6a3809ec6d',
    messagingSenderId: '302709623576',
    projectId: 'fruit-hub-763b2',
    storageBucket: 'fruit-hub-763b2.firebasestorage.app',
    androidClientId: '302709623576-op67acv03a8jli7ri4dhagg8l018tuj7.apps.googleusercontent.com',
    iosClientId: '302709623576-tnmk92uu43navv7r4rqj8j0u0vct830k.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboaerd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYoNrToJ2ombPSWw1zRB2_Ag3dR9ROlko',
    appId: '1:302709623576:web:04a071b01246b2b009ec6d',
    messagingSenderId: '302709623576',
    projectId: 'fruit-hub-763b2',
    authDomain: 'fruit-hub-763b2.firebaseapp.com',
    storageBucket: 'fruit-hub-763b2.firebasestorage.app',
    measurementId: 'G-D1YCBWH6PZ',
  );
}
